Ppo 30 test directory parsing
eastgenomics/test_directory_parser pull request #1
Opened 2022-07-05 12:43 UTC by Yu-jinKim

2022-07-05 12:43 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`test_directory_parser/utils.py`](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py):

> [Line 56:80](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L56): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 79 characters)
> [Line 57:80](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L57): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 59:34](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L59): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 62:80](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 68:80](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L68): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 74:80](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L74): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 75:80](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L75): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2022-07-05 13:14 UTC, jethror1 requested changes
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 1 of 8 files reviewed, 19 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`main.py` line 30 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOFPACaE1CTd1J7HQ:-N6DOFPB05PJGjjyQaGe:b-70b588) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/main.py#L30)):*
> ```Python
>         pass
>     else:
>         raise Exception("?")
> ```

what is this `raise Exception("🤷")`
___
*[`README.md` line 4 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOkhf-OYf5_6U7F3q:-N6DOkhf-OYf5_6U7F3r:bxd0ui4) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L4)):*
> ```Markdown
> Script(s) to parse the test directories
> 
> ## Beforehand
> ```

beforehand?
___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOolc3y4Y3Bu920f_:-N6DOolc3y4Y3Bu920fa:b32wxs) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L8)):*
> ```Markdown
> ### HGNC dump
> 
> To generate the HGNC dump, you can go there: https://www.genenames.org/download/custom/
> ```

to



_Code quote:_
```Markdown
there
```
___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOtlP3M-idocClXBD:-N6DOtlP3M-idocClXBE:bue1067) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L15)):*
> ```Markdown
> - Approved symbol
> - Alias symbols
> - Previous symbols
> ```

an example head of the downloaded file or similar might be useful
___
*[`README.md` line 19 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DUFQ5BLPEsmUudCvp:-N6DUFQ5BLPEsmUudCvq:b9ie93m) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L19)):*
> ```Markdown
> ### Test directory
> 
> The rare disease and cancer test directories are downloadable here: https://www.england.nhs.uk/publication/national-genomic-test-directories/
> ```

this doesn't handle cancer does it? can this be added here that it is just currently for RD
___
*[`README.md` line 51 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DP7kgEp1Cel18mNup:-N6DP7kgEp1Cel18mNuq:b-aflr8e) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L51)):*
> ```Markdown
> 
> ```bash
> source ../../envs/test_directory_parser/bin/activate
> ```

what is this?
___
*[`test_directory_parser/clinical_indication.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPMZT5UHVdpziqTKl:-N6DPMZT5UHVdpziqTKm:blfvipa) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/clinical_indication.py#L13)):*
> ```Python
>         self.clean_panels(hgnc_dump)
> 
>     def clean_panels(self, hgnc_dump):
> ```

string doc
___
*[`test_directory_parser/clinical_indication.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPahoDXgH27TIG9QR:-N6DPahoDXgH27TIG9QS:b-les6jb) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/clinical_indication.py#L19)):*
> ```Python
>         panels_semicolon = [p.strip() for p in panels.split(";")]
> 
>         if panels_comma == panels_semicolon:
> ```

what is panels_comma vs panels_semicolon? 
___
*[`test_directory_parser/rare_disease.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DO6AKAVQZMboqOBbQ:-N6DO6AKAVQZMboqOBbR:bc7gl4l) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/rare_disease.py#L3)):*
> ```Python
> import json
> 
> import pandas as pd
> ```

so proud :heart: 



_Code quote:_
```Python
import pandas as pd
```
___
*[`test_directory_parser/rare_disease.py` line 14 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPmWI2tb6Zrjwnkmd:-N6DPmWI2tb6Zrjwnkme:b-p2oh7b) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/rare_disease.py#L14)):*
> ```Python
> 
> 
> def parse_rare_disease_td(test_directory, config):
> ```

string doc, maybe for whole script too if this is going to expand
___
*[`test_directory_parser/rare_disease.py` line 18 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DUPSpA3hNJrKDBf9e:-N6DUPSpA3hNJrKDBf9f:b-kldexj) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/rare_disease.py#L18)):*
> ```Python
>         test_directory, sheet_name=None, header=config["header_index"]
>     )
> ```

since the test directory is a dirty excel, do we need to do any asserting of data structure before attempting to parse it to ensure they haven't changed the structure between versions?
___
*[`test_directory_parser/test_directory.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPy-s0bYtocE49Djc:-N6DPy-s0bYtocE49Djd:blfvipa) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/test_directory.py#L12)):*
> ```Python
>         self.hgnc_dump = hgnc_dump
> 
>     def setup_clinical_indications(self):
> ```

string doc
___
*[`test_directory_parser/utils.py` line 17 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DQ4Pw8aUEJPs4Pdil:-N6DQ4Pw8aUEJPs4Pdim:b-9frizk) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L17)):*
> ```Python
>     now = datetime.datetime.now()
>     date = now.strftime("%y%m%d")
>     return date
> ```

any reason for this not to be a oneliner?

`return datetime.datetime.now().strftime("%y%m%d")`



_Code quote:_
```Python
datetime.datetime.now()
```
___
*[`test_directory_parser/utils.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DS7pyD0QicLi9D0YZ:-N6DS7pyD0QicLi9D0Y_:b-rg4o4c) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L22)):*
> ```Python
> def parse_tsv(tsv):
>     data = pd.read_csv(tsv, delimiter="\t")
>     noned_data = data.where(pd.notnull(data), None)
> ```

noned data? 
___
*[`test_directory_parser/utils.py` line 78 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DSXMM2b4qntssz9hu:-N6DSXMM2b4qntssz9hv:bocx9lw) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L78)):*
> ```Python
> 
>             # check the size of the dataframes and do the appropriate action
>             if len(df_previous_symbols) == 0 and len(df_alias_symbols) == 0:
> ```

can you explain why each is appropriate?
___
*[`test_directory_parser/utils.py` line 105 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DSgdd4ew3eC0tuPWo:-N6DSgdd4ew3eC0tuPWp:b-rx9ont) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L105)):*
> ```Python
>     """
> 
>     match = regex.match(pattern, target)
> ```

this can just be `return regex.match(pattern, target)` right?
___
*[`test_directory_parser/utils.py` line 139 at r1](https://reviewable.io/reviews/eastgeno [...]

2022-07-05 13:20 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 1 of 8 files reviewed, 19 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`main.py` line 30 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOFPACaE1CTd1J7HQ:-N6DUvHI3R9wurwS_Z3R:b-sabsda) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/main.py#L30)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is this `raise Exception("🤷")`
</blockquote></details>

remnants of the start of the project, will remove
___
*[`README.md` line 4 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOkhf-OYf5_6U7F3q:-N6DV3xv3Jmp049V7CC-:biprnas) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L4)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

beforehand?
</blockquote></details>

list of stuff to have ready before running the code felt too wordy
___
*[`test_directory_parser/rare_disease.py` line 18 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DUPSpA3hNJrKDBf9e:-N6DVP4G9KGjrf-Lp91g:b-5imejl) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/rare_disease.py#L18)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

since the test directory is a dirty excel, do we need to do any asserting of data structure before attempting to parse it to ensure they haven't changed the structure between versions?
</blockquote></details>

that's why i have config files specific to test directory versions
___
*[`test_directory_parser/utils.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DTj6-1HuH-rCDBzJq:-N6DVlxUElBJNNG9fJhG:b-hgpzvo) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L154)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is this for? if there's commas in the panel, is a comma separated string the right thing to use?
</blockquote></details>

i.e. `panel_with, commas` gets broken up like so `["panel_with", " commas"] i want to go back to the original name


<!-- Sent from Reviewable.io -->

2022-07-05 13:39 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 1 of 8 files reviewed, 19 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`README.md` line 4 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOkhf-OYf5_6U7F3q:-N6DYizP0lhaZDbuxBKn:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L4)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

list of stuff to have ready before running the code felt too wordy
</blockquote></details>

Done.
___
*[`README.md` line 8 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOolc3y4Y3Bu920f_:-N6DYhwM0ED9_pyJlyA8:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L8)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

to
</blockquote></details>

Done.
___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DOtlP3M-idocClXBD:-N6DYiLwBjOPCyTt-Px-:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L15)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

an example head of the downloaded file or similar might be useful
</blockquote></details>

Done.
___
*[`README.md` line 19 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DUFQ5BLPEsmUudCvp:-N6DZOBR7KnJ99lMLKs_:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L19)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this doesn't handle cancer does it? can this be added here that it is just currently for RD
</blockquote></details>

Done.
___
*[`README.md` line 51 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DP7kgEp1Cel18mNup:-N6DZROR5A1_W-tHyPQW:b-l3zqj6) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L51)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is this?
</blockquote></details>

environment


<!-- Sent from Reviewable.io -->

2022-07-06 09:34 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 1 of 8 files reviewed, 19 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`test_directory_parser/clinical_indication.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPMZT5UHVdpziqTKl:-N6DaHVS0tqoj-c-WTP3:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/clinical_indication.py#L13)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

string doc
</blockquote></details>

Done.
___
*[`test_directory_parser/clinical_indication.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPahoDXgH27TIG9QR:-N6DaI204vjlZyGOHgen:bctl40t) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/clinical_indication.py#L19)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is panels_comma vs panels_semicolon? 
</blockquote></details>

targets can be separated by commas or semicolons
___
*[`test_directory_parser/rare_disease.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DO6AKAVQZMboqOBbQ:-N6DaPJd4y5cVCV9Bz16:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/rare_disease.py#L3)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

so proud :heart: 
</blockquote></details>

Done.
___
*[`test_directory_parser/rare_disease.py` line 14 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPmWI2tb6Zrjwnkmd:-N6DbUcD5akUdl1g__gN:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/rare_disease.py#L14)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

string doc, maybe for whole script too if this is going to expand
</blockquote></details>

Done.
___
*[`test_directory_parser/test_directory.py` line 12 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPy-s0bYtocE49Djc:-N6Hr1gB1QVu4i_Ha17i:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/test_directory.py#L12)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

string doc
</blockquote></details>

Done.
___
*[`test_directory_parser/utils.py` line 17 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DQ4Pw8aUEJPs4Pdil:-N6Hr2J-32XYHSjnCAWP:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L17)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

any reason for this not to be a oneliner?

`return datetime.datetime.now().strftime("%y%m%d")`
</blockquote></details>

Done.
___
*[`test_directory_parser/utils.py` line 105 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DSgdd4ew3eC0tuPWo:-N6Hr3Xu6Ru8bZe7klWR:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L105)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this can just be `return regex.match(pattern, target)` right?
</blockquote></details>

Done.
___
*[`test_directory_parser/utils.py` line 139 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DTS0t6BRGqxMK_zL1:-N6Hr4RE0dZeLGHdTFhw:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L139)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can this be a single gene? if so it isnt handled
</blockquote></details>

Done.
___
*[`test_directory_parser/utils.py` line 145 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DT_FF34HReRXllDC6:-N6Hr5-C2YawIu0w8Bu5:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L145)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what happens if one isn't found? will it just be missed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-06 10:27 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 1 of 8 files reviewed, 19 unresolved discussions (waiting on @jethror1)

___
*[`test_directory_parser/utils.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DS7pyD0QicLi9D0YZ:-N6Hte_Q0QQN5JzAQWxF:b-mbo50w) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L22)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

noned data? 
</blockquote></details>

data with nones instead of NA
___
*[`test_directory_parser/utils.py` line 78 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DSXMM2b4qntssz9hu:-N6I24ieDxTcyxERBMCm:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L78)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you explain why each is appropriate?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-06 11:12 UTC, jethror1 requested changes
> Reviewed 1 of 8 files at r1, 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`README.md` line 51 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DP7kgEp1Cel18mNup:-N6I8RZS33oR1fYV8iH7:b-dirsjp) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L51)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

environment
</blockquote></details>

this is specific to you right? should it be in the readme since you're not including anything extra in the repo?
___
*[`test_directory_parser/clinical_indication.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPahoDXgH27TIG9QR:-N6I8k889VYKmW0lguVw:bx6ljeu) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/clinical_indication.py#L19)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

targets can be separated by commas or semicolons
</blockquote></details>

I don't get why you're comparing if there's two lists of panels here that you're comparing? what is original targets?
___
*[`test_directory_parser/utils.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DS7pyD0QicLi9D0YZ:-N6IA15oEY5Og6wNQdWH:b-1j2l34) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L22)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

data with nones instead of NA
</blockquote></details>

ohhh is this meant to replaced any null type data with None? a comment and/or docstring would help
___
*[`test_directory_parser/utils.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DTj6-1HuH-rCDBzJq:-N6ICE6W1v2BkjfGZwuo:b-7niat0) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L154)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i.e. `panel_with, commas` gets broken up like so `["panel_with", " commas"] i want to go back to the original name
</blockquote></details>

will you get cases of multiple panels mixed like`['panel_with', 'commas', 'panel2', 'panel3']`?
___
*[`test_directory_parser/utils.py` line 88 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6IASSC3EPmkK0TuSME:-N6IASSC3EPmkK0TuSMF:bcomgtj) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/a8fe1a6bfac99e59197d8144ac4229869ce90a92/test_directory_parser/utils.py#L88)):*
> ```Python
>                 # found previous and alias symbols, cry
>                 print(
>                     "Couldn't find a non umbiguous HGNC id for "
> ```

ambiguous



_Code quote:_
```Python
umbiguous
```
___
*[`test_directory_parser/utils.py` line 96 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6IAhUKEFhZtiApf0oy:-N6IAhUKEFhZtiApf0oz:b8lxssw) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/a8fe1a6bfac99e59197d8144ac4229869ce90a92/test_directory_parser/utils.py#L96)):*
> ```Python
>             raise Exception(f"'{gene_symbol}' escaped checks")
>     else:
>         return [hgnc_id for hgnc_id in data][0]
> ```

why do you need to do a list comp and select first here? would it be more than one item and is it appropriate to take the first?
___
*[`test_directory_parser/utils.py` line 118 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6IBLv6EYHSDOhSNvY2:-N6IBLv7D6xK0aUvrORO:b-3nj5uq) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/a8fe1a6bfac99e59197d8144ac4229869ce90a92/test_directory_parser/utils.py#L118)):*
> ```Python
>         # we are dealing with genes
>         for panel in panels:
>             if regex.match(r"[A-Z]+[A-Z0-9]+", panel):
> ```

I don't get the first `if regex.match..`, the `panels` argument takes a list, and if the first doesn't matches a regex and don't enter here.

are you meant to be looping over each panel in that passed list and checking it with the below logic, and if it doesn't match the regex drop to the bottom? or am I missing something? the many if elses are hurting my eyes


<!-- Sent from Reviewable.io -->

2022-07-06 14:46 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 51 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DP7kgEp1Cel18mNup:-N6IGhByCCZRc7-LzgrM:b-jki7cj) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/README.md#L51)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this is specific to you right? should it be in the readme since you're not including anything extra in the repo?
</blockquote></details>

no? I have a requirements.txt file in the repo
___
*[`test_directory_parser/clinical_indication.py` line 19 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DPahoDXgH27TIG9QR:-N6IGljO-HPZZgl_1CaA:b-ymduco) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/clinical_indication.py#L19)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I don't get why you're comparing if there's two lists of panels here that you're comparing? what is original targets?
</blockquote></details>

this first comparison allows me to filter some test cases quickly:
CI1 -> MEN1;AIP;CDKN1B;CDC73
CI2 -> NLRP5, NLRP7, NLRP2, PAD16, KHDC3L
CI3 -> Familial tumoral calcinosis (552)

CI1:
- comma splitting: `["MEN1;AIP;CDKN1B;CDC73"]`
- semi colon splitting: `["MEN1", "AIP", "CDKN1B", "CDC73"]`

CI2:
- comma splitting: `["NLRP5", "NLRP7", "NLRP2", "PAD16", "KHDC3L"]`
- semi colon splitting: `["NLRP5, NLRP7, NLRP2, PAD16, KHDC3L"]`

CI3:
- comma splitting: `["Familial tumoral calcinosis (552)"]`
- semi colon splitting: `["Familial tumoral calcinosis (552)"]`

The comparison of the 2 lists allows me to take care of the single element lists which are most likely to be a panelapp panel or some garbage target
___
*[`test_directory_parser/utils.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DS7pyD0QicLi9D0YZ:-N6II_ST6p-BLtCtlfnK:bgt2pdu) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L22)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ohhh is this meant to replaced any null type data with None? a comment and/or docstring would help
</blockquote></details>

is that not how null data is replaced? I googled and copy pasted
___
*[`test_directory_parser/utils.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DTj6-1HuH-rCDBzJq:-N6IyLSPDSLZPVY21OwJ:b1bnk5d) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L154)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will you get cases of multiple panels mixed like`['panel_with', 'commas', 'panel2', 'panel3']`?
</blockquote></details>

i'm not smart enough to fix that
___
*[`test_directory_parser/utils.py` line 88 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6IASSC3EPmkK0TuSME:-N6IIgiZB5BxSCUkj2a4:b-yg1uf) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/a8fe1a6bfac99e59197d8144ac4229869ce90a92/test_directory_parser/utils.py#L88)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ambiguous
</blockquote></details>

i english much lots
___
*[`test_directory_parser/utils.py` line 96 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6IAhUKEFhZtiApf0oy:-N6IJL2v9fne-P5JWlLm:brr77) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/a8fe1a6bfac99e59197d8144ac4229869ce90a92/test_directory_parser/utils.py#L96)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why do you need to do a list comp and select first here? would it be more than one item and is it appropriate to take the first?
</blockquote></details>

data is a dataframe so i don't think i can just take the first element, can i?
___
*[`test_directory_parser/utils.py` line 118 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6IBLv6EYHSDOhSNvY2:-N6IZVEj0z8prtXeBr_Y:b51kggp) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/a8fe1a6bfac99e59197d8144ac4229869ce90a92/test_directory_parser/utils.py#L118)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I don't get the first `if regex.match..`, the `panels` argument takes a list, and if the first doesn't matches a regex and don't enter here.

are you meant to be looping over each panel in that passed list and checking it with the below logic, and if it doesn't match the regex drop to the bottom? or am I missing something? the many if elses are hurting my eyes
</blockquote></details>

added comments


<!-- Sent from Reviewable.io -->

2022-07-06 15:40 UTC, jethror1 requested changes
> Reviewed 1 of 2 files at r2, 2 of 6 files at r3, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`test_directory_parser/utils.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DS7pyD0QicLi9D0YZ:-N6J1xSH6zElEjoSUapW:bp5e9fx) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L22)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is that not how null data is replaced? I googled and copy pasted
</blockquote></details>

after thinking about it yes thats fine, but without really knowing pandas its not, and the lack of a docstring or comment didnt help
___
*[`test_directory_parser/utils.py` line 154 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6DTj6-1HuH-rCDBzJq:-N6J9qip81WUwhh5VkzG:b-qh11n6) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/9168849203f3042539550998e44323fed674abad/test_directory_parser/utils.py#L154)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i'm not smart enough to fix that
</blockquote></details>

yeah I agree, no to that
___
*[`test_directory_parser/utils.py` line 96 at r4](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-N6IAhUKEFhZtiApf0oy:-N6J3MtmCilA_3LaepfD:b-w2qck0) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/a8fe1a6bfac99e59197d8144ac4229869ce90a92/test_directory_parser/utils.py#L96)):*
from above it looks like its just one column, so will be a series. So here you iterate over it to force it into a list and then select the first, right?

this would be a better way using `.loc`:
```
>>> df = pd.DataFrame([{'a':'this'}, {'a':'that'}, {'a':'thing'}])
>>> df
       a
0   this
1   that
2  thing
>>> df.a.loc[0]
'this'
```

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html


<!-- Sent from Reviewable.io -->

2022-07-06 16:09 UTC, jethror1 approved these changes
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:09 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JG_rt4orGvEjdrfr0:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, jethror1 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JGcGG2ktcJHfIUOyK:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JGe3rD1bw1v9LE9Hn:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, jethror1 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JGfFlDRtISIp06CC_:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JGgIs5PqPDuEG-LFT:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, jethror1 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JGhK21Q8PUb0uynIr:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JGiK14pW9Oixwj_Ik:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, jethror1 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JGjO89tHV-MXmpS_5:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, jethror1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/1#-:-N6JGkVS38LNHCQZjkrT:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2022-07-06 16:10 UTC, merged